"""rename address

Revision ID: 442ff30b7903
Revises: 4f7f2ca2f643
Create Date: 2025-09-21 09:36:46.534908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442ff30b7903'
down_revision = '4f7f2ca2f643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments','address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',new_column_name='address')
    # ### end Alembic commands ###
