"""rename department

Revision ID: 4f7f2ca2f643
Revises: fbfa3b280fb1
Create Date: 2025-09-20 19:14:28.188631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7f2ca2f643'
down_revision = 'fbfa3b280fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.rename_table('departments','department')
    # ### end Alembic commands ###
